<a href="https://colab.research.google.com/github/LucasLucena001/Actions_Predict/blob/main/Actions_Predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import math
%pip install yfinance
import yfinance as yf
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense, LSTM
import matplotlib.pyplot as plt
from datetime import datetime
from datetime import timedelta
pd.options.mode.chained_assignment = None

%pip install tensorflow

In [3]:
acao = "PETR4.SA"

inicio = "2015-12-31"
final = "2024-03-23"

dados_acao = yf.download(acao, inicio, final)

dados_acao

[*********************100%%**********************]  1 of 1 completed


Open       High        Low      Close  Adj Close    Volume
Date                                                                       
2016-01-04   6.570000   7.030000   6.550000   6.870000   2.267931  45962100
2016-01-05   6.920000   7.000000   6.620000   6.680000   2.205208  29446700
2016-01-06   6.530000   6.540000   6.400000   6.400000   2.112775  67507200
2016-01-07   6.190000   6.430000   6.080000   6.260000   2.066557  57387900
2016-01-08   6.380000   6.450000   6.130000   6.270000   2.069859  52100300
...               ...        ...        ...        ...        ...       ...
2024-03-18  36.410000  36.720001  35.500000  36.340000  32.923672  35326100
2024-03-19  36.389999  36.849998  35.560001  36.070000  32.679054  48540800
2024-03-20  36.230000  36.740002  35.810001  36.700001  33.249828  39017900
2024-03-21  36.849998  37.060001  35.680000  35.700001  32.343838  47220200
2024-03-22  35.900002  36.220001  35.430000  36.049999  32.660934  34426800

[2047 rows x 6 columns]

In [4]:
cotacao = dados_acao['Close'].to_numpy().reshape(-1, 1)

cotacao

array([[ 6.86999989],
       [ 6.67999983],
       [ 6.4000001 ],
       ...,
       [36.70000076],
       [35.70000076],
       [36.04999924]])

In [5]:
tamanho_dados_treinamento = int(len(cotacao) * 0.8)

tamanho_dados_treinamento

1637

In [6]:
escalador = MinMaxScaler(feature_range=(0, 1))

dados_entre_0_e_1_treinamento = escalador.fit_transform(cotacao[0: tamanho_dados_treinamento, :])

dados_entre_0_e_1_teste = escalador.transform(cotacao[tamanho_dados_treinamento: , :])

dados_entre_0_e_1 = list(dados_entre_0_e_1_treinamento.reshape(
    len(dados_entre_0_e_1_treinamento))) + list(dados_entre_0_e_1_teste.reshape(len(dados_entre_0_e_1_teste)))


dados_entre_0_e_1 = np.array(dados_entre_0_e_1).reshape(len(dados_entre_0_e_1), 1)

dados_entre_0_e_1

array([[0.0834375 ],
       [0.0775    ],
       [0.06875001],
       ...,
       [1.015625  ],
       [0.984375  ],
       [0.99531245]])

In [7]:
dados_para_treinamento = dados_entre_0_e_1[0:tamanho_dados_treinamento, :]

treinamento_x = []

treinamento_y = []

for i in range(60, len(dados_para_treinamento)):

    treinamento_x.append(dados_para_treinamento[i-60:i, 0])

    treinamento_y.append(dados_para_treinamento[i, 0])

    if i <= 60:

        print(treinamento_x)
        print(treinamento_y)

[array([0.0834375 , 0.0775    , 0.06875001, 0.06437501, 0.0646875 ,
       0.05906251, 0.04156251, 0.0334375 , 0.04656251, 0.03031251,
       0.01875001, 0.014375  , 0.0071875 , 0.00937501, 0.0065625 ,
       0.        , 0.01156251, 0.0125    , 0.02000001, 0.01625   ,
       0.00312501, 0.0090625 , 0.01656251, 0.010625  , 0.0034375 ,
       0.00093751, 0.0078125 , 0.01156251, 0.00750001, 0.015     ,
       0.01218751, 0.00812501, 0.02625   , 0.02250001, 0.0209375 ,
       0.0215625 , 0.0209375 , 0.029375  , 0.0346875 , 0.04531251,
       0.07406251, 0.094375  , 0.0990625 , 0.1021875 , 0.10625   ,
       0.1171875 , 0.12156251, 0.10000001, 0.07531251, 0.0946875 ,
       0.12187501, 0.1225    , 0.12062502, 0.12218749, 0.11187501,
       0.1128125 , 0.13249999, 0.13406249, 0.13249999, 0.12843752])]
[0.12999999135732676]


In [8]:
dados_para_treinamento = dados_entre_0_e_1[0: tamanho_dados_treinamento, :]

#dados que serão usados para gerar o resultado
treinamento_x = []
#cotação que aconteceu de fato
treinamento_y = []


for i in range(60, len(dados_para_treinamento)):

    #60 ultimos dias
    treinamento_x.append(dados_para_treinamento[i - 60: i, 0])
    #cotacao
    treinamento_y.append(dados_para_treinamento[i, 0])

    if i <= 61:

        print(treinamento_x)
        print(treinamento_y)



[array([0.0834375 , 0.0775    , 0.06875001, 0.06437501, 0.0646875 ,
       0.05906251, 0.04156251, 0.0334375 , 0.04656251, 0.03031251,
       0.01875001, 0.014375  , 0.0071875 , 0.00937501, 0.0065625 ,
       0.        , 0.01156251, 0.0125    , 0.02000001, 0.01625   ,
       0.00312501, 0.0090625 , 0.01656251, 0.010625  , 0.0034375 ,
       0.00093751, 0.0078125 , 0.01156251, 0.00750001, 0.015     ,
       0.01218751, 0.00812501, 0.02625   , 0.02250001, 0.0209375 ,
       0.0215625 , 0.0209375 , 0.029375  , 0.0346875 , 0.04531251,
       0.07406251, 0.094375  , 0.0990625 , 0.1021875 , 0.10625   ,
       0.1171875 , 0.12156251, 0.10000001, 0.07531251, 0.0946875 ,
       0.12187501, 0.1225    , 0.12062502, 0.12218749, 0.11187501,
       0.1128125 , 0.13249999, 0.13406249, 0.13249999, 0.12843752])]
[0.12999999135732676]
[array([0.0834375 , 0.0775    , 0.06875001, 0.06437501, 0.0646875 ,
       0.05906251, 0.04156251, 0.0334375 , 0.04656251, 0.03031251,
       0.01875001, 0.014375  , 0.007

In [9]:
treinamento_x, treinamento_y = np.array(treinamento_x), np.array(treinamento_y)

print(treinamento_x)

treinamento_x = treinamento_x.reshape(treinamento_x.shape[0], treinamento_x.shape[1], 1)

print(treinamento_x)

[[0.0834375  0.0775     0.06875001 ... 0.13406249 0.13249999 0.12843752]
 [0.0775     0.06875001 0.06437501 ... 0.13249999 0.12843752 0.12999999]
 [0.06875001 0.06437501 0.0646875  ... 0.12843752 0.12999999 0.104375  ]
 ...
 [0.81406248 0.87093747 0.86906243 ... 0.78531248 0.82812501 0.83781249]
 [0.87093747 0.86906243 0.90187502 ... 0.82812501 0.83781249 0.84843749]
 [0.86906243 0.90187502 0.87374998 ... 0.83781249 0.84843749 0.87781251]]
[[[0.0834375 ]
  [0.0775    ]
  [0.06875001]
  ...
  [0.13406249]
  [0.13249999]
  [0.12843752]]

 [[0.0775    ]
  [0.06875001]
  [0.06437501]
  ...
  [0.13249999]
  [0.12843752]
  [0.12999999]]

 [[0.06875001]
  [0.06437501]
  [0.0646875 ]
  ...
  [0.12843752]
  [0.12999999]
  [0.104375  ]]

 ...

 [[0.81406248]
  [0.87093747]
  [0.86906243]
  ...
  [0.78531248]
  [0.82812501]
  [0.83781249]]

 [[0.87093747]
  [0.86906243]
  [0.90187502]
  ...
  [0.82812501]
  [0.83781249]
  [0.84843749]]

 [[0.86906243]
  [0.90187502]
  [0.87374998]
  ...
  [0.8378